<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_comments.php 
 * 
 * Contao extension: efg 1.14.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2010 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Thomas Kuhn (tom) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_comments']['tl_formdata'] = "Formulardaten";
 
?>
