<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_efg_modules.php 
 * 
 * Contao extension: efg 1.14.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2010 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Thomas Kuhn (tom) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['formdata'] = "Formular-Daten";
$GLOBALS['TL_LANG']['MOD']['efg'] = "Formular-Daten";
$GLOBALS['TL_LANG']['MOD']['feedback']['0'] = "Feedback";
$GLOBALS['TL_LANG']['MOD']['feedback']['1'] = "Gespeicherte Daten aus Formularen.";
$GLOBALS['TL_LANG']['MOD']['formdata_from'] = "Gespeicherte Daten aus Formular";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['0'] = "Auflistung Formular-Daten";
$GLOBALS['TL_LANG']['MOD']['formdatalisting']['1'] = "Mit diesem Modul können Sie eine beliebige Formular-Daten-Tabelle im Frontend auflisten.";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['0'] = "Auflistung Formular-Daten";
$GLOBALS['TL_LANG']['FMD']['formdatalisting']['1'] = "Verwenden Sie dieses Modul dazu, die Daten einer beliebigen Formular-Daten-Tabelle im Frontend aufzulisten.";
 
?>
