<?php
/**
 * TL_ROOT/system/modules/videobox_vimeo/languages/lv/default.php 
 * 
 * Contao extension: videobox_vimeo 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : David Enke 2010 
 * License   : GNU/GPL 
 * Author    : David Enke (david.enke), www.davidenke.de 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['VideoTypes']['vimeo'] = "Vimeo";
$GLOBALS['TL_LANG']['VideoBox']['vimeo_noscript'] = "Diemžēl jūs nevarat noskatīties video ar nosaukumu \"% s\" bez Javascript.";
$GLOBALS['TL_LANG']['VideoBox']['vimeo_noflash'] = "Diemžēl jūs nevarat noskatīties video ar nosaukumu \"% s\" bez Adobe Flash Player.";
 
?>
