<?php
/**
 * TL_ROOT/system/modules/videobox_vimeo/languages/lv/tl_videobox.php 
 * 
 * Contao extension: videobox_vimeo 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : David Enke 2010 
 * License   : GNU/GPL 
 * Author    : David Enke (david.enke), www.davidenke.de 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox']['vimeo_id']['0'] = "Vimeo-ID";
$GLOBALS['TL_LANG']['tl_videobox']['vimeo_id']['1'] = "Norādīte Jūsu Vimeo video ID. ID ir <strong>iezīmētā</strong> adreses daļa: http://http://vimeo.com/<strong>16247471</strong>";
$GLOBALS['TL_LANG']['tl_videobox']['vimeo_legend'] = "Vimeo video";
 
?>
