<?php
/**
 * TL_ROOT/system/modules/videobox_vimeo/languages/lv/tl_videobox_settings.php 
 * 
 * Contao extension: videobox_vimeo 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : David Enke 2010 
 * License   : GNU/GPL 
 * Author    : David Enke (david.enke), www.davidenke.de 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_legend'] = "Vimeo video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_template']['0'] = "Veidne";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_template']['1'] = "Izvēleties veidni priekš Vimeo video.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_size']['0'] = "Izmērs";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_size']['1'] = "Iespējams norādīt video platuma un augstuma vērtības.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_autoplay']['0'] = "Automātiska atskaņošana";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_autoplay']['1'] = "Norāda vai video attēlošana tiks veikta automātiski pēc atskaņotāja ielādes vai nē.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_color']['0'] = "Krāsa";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_color']['1'] = "Šī krāsa tonē atskaņotāja kontroles.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showbyline']['0'] = "Rādīt video autora parakstu";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showbyline']['1'] = "Parāda video autora parakstu pirms video atskaņošanas sākuma.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showtitle']['0'] = "Parādīt video nosaukumu";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showtitle']['1'] = "Parāda video nosaukumu pirms video atskaņošanas sākuma.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showportrait']['0'] = "Parādīt lietotāja attēlu";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showportrait']['1'] = "Parāda lietotāja attēlu pirms video atskaņošanas sākuma.";
 
?>
