<?php
/**
 * TL_ROOT/system/modules/googleanalytics/languages/cs/tl_page.php 
 * 
 * Contao extension: googleanalytics 1.3.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2011-2012 Jan Theofel, 2010 ETES GmbH 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['0'] = "Google Analytics ID";
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['1'] = "ID pro Google Analytics (formát: \"UA-xxxxxxx-x\")";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['0'] = "Anonymní IP";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['1'] = "Anonymizovat IP před odesláním na Google.";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['0'] = "Povolit měření času";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['1'] = "Umožňuje měření času načítání stránky.";
$GLOBALS['TL_LANG']['tl_page']['ga_eventtracking']['0'] = "Přidat sledování událostí";
$GLOBALS['TL_LANG']['tl_page']['ga_eventtracking']['1'] = "Přidejte javascriptový kód pro ruční sledování událostí.";
$GLOBALS['TL_LANG']['tl_page']['ga_externaltracking']['0'] = "Přidat sledování externí URL";
$GLOBALS['TL_LANG']['tl_page']['ga_externaltracking']['1'] = "Přidejte javascriptový kód pro manuální externí URL sledování.";
$GLOBALS['TL_LANG']['tl_page']['ga_setdomainname']['0'] = "Nastavit název domény pro cookie";
$GLOBALS['TL_LANG']['tl_page']['ga_setdomainname']['1'] = "Použijte tento název domény pro sledovací soubory cookie.";
$GLOBALS['TL_LANG']['tl_page']['ga_addlinktracking']['0'] = "Sledovat všechny externí odkazy";
$GLOBALS['TL_LANG']['tl_page']['ga_addlinktracking']['1'] = "Aktivuje sledování pro všechny externí odkazy. Důležité: Toto odstraní všechny události onClick pro externí odkazy. Pouze v případě, že již obsahují gaTrackLink nebo gaTrackEvent nebudou odstraněny.";
$GLOBALS['TL_LANG']['tl_page']['ga_titlelinktracking']['0'] = "Název skupiny pro automaticky sledovat odkazy";
$GLOBALS['TL_LANG']['tl_page']['ga_titlelinktracking']['1'] = "Název pro skupinu událostí v Google Analytics automaticky sledovány události. Adresa URL se používá jako akční hodnota.";
$GLOBALS['TL_LANG']['tl_page']['ga_bounceseconds']['0'] = "Navštivte čas definován jako Bounce (sekund)";
$GLOBALS['TL_LANG']['tl_page']['ga_bounceseconds']['1'] = "Návštěvy s časem kratším, než je tato, jsou definovány jako odrazit. 0 vypnout. Doporučené hodnoty: 5-10 sekund.";
$GLOBALS['TL_LANG']['tl_page']['googleanalytics_legend'] = "Google Analytics";
 
?>
