<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ja/tl_settings.php 
 * 
 * Contao extension: BackupDB 1.5.0 stable 
 * Japanese translation file 
 * 
 * Copyright : 2007-2012 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['0'] = "ウェブサイトのテンプレートのデータテーブル";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['1'] = "ウェブサイトのテンプレートに含めるテーブルのプリフィックスやテーブルをコンマで区切ったリストで入力してください。Contaoのコアのすべてのテーブルは<em>tl_</em>で始まっています。機能拡張のカタログのテーブルは<em>cat_</em>で始まっているでしょう。";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['0'] = "AutoBackupDBでバックアップする数";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['1'] = "AutoBackupDBで作成するバックアップの数で初期値は3です。最新のバックアップは常に<em>AutoBackupDB-1.sql</em>というファイルとなります。";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['0'] = "ウェブサイトのテンプレートの別のパス";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['1'] = "パスの初期値は<em>templates</em>です。ウェブサイトのテンプレートを保持する異なるディレクトリを指定できます。";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "BackupDBの設定";
 
?>
