<?php
/**
 * TL_ROOT/system/modules/videobox/languages/it/tl_videobox.php 
 * 
 * Contao extension: videobox 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['0'] = "Titolo del video";
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['1'] = "Indicare il titolo del video";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['0'] = "Tipologia video";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['1'] = "Selezionare il tipo di video";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['0'] = "ID Video Youtube";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['1'] = "Inserire l'ID del video Youtube ceh si vuole aggiungere. L'id è la parte in <strong>grassetto</strong> dell'indirizzo Youtube: http://www.youtube.com/watch?v=<strong>SGeZYednWtI</strong>";
$GLOBALS['TL_LANG']['tl_videobox']['title_legend'] = "Impistazioni predefinite";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_legend'] = "Video Youtube";
$GLOBALS['TL_LANG']['tl_videobox']['new']['0'] = "Nuovo video";
$GLOBALS['TL_LANG']['tl_videobox']['new']['1'] = "Aggiungi un nuovo video";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['0'] = "Modifica video";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['1'] = "Modifica il video con id %s";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['0'] = "Copia video";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['1'] = "Copia il video con id %s";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['0'] = "Sposta video";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['1'] = "Sposta il video con id %s";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['0'] = "Elimina video";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['1'] = "Elimina il video con id %s";
$GLOBALS['TL_LANG']['tl_videobox']['show']['0'] = "Mostra dettagli";
$GLOBALS['TL_LANG']['tl_videobox']['show']['1'] = "Mostra i dettagli del video con id %s";
 
?>
