<?php
/**
 * TL_ROOT/system/modules/googleanalytics/languages/ja/tl_page.php 
 * 
 * Contao extension: googleanalytics 1.3.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2011 Jan Theofel, 2010 ETES GmbH 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['0'] = "GoogleアナリティクスのID";
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['1'] = "GoogleアナリティクスのID、ウェブプロパティIDを入力してください。(書式: \"UA-xxxxxx-x\")";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['0'] = "IPアドレスを匿名化";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['1'] = "Googleに送信する前にIPアドレスを匿名化します。";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['0'] = "ページのロードの追跡を有効";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['1'] = "ページのロード時間の計測を有効にします。";
$GLOBALS['TL_LANG']['tl_page']['ga_eventtracking']['0'] = "イベントの追跡を追加";
$GLOBALS['TL_LANG']['tl_page']['ga_eventtracking']['1'] = "手作業によるイベントの追跡のためのJavascriptコードを追加します。";
$GLOBALS['TL_LANG']['tl_page']['ga_externaltracking']['0'] = "外部の追跡を追加";
$GLOBALS['TL_LANG']['tl_page']['ga_externaltracking']['1'] = "手作業による外部のURLの追跡のためのJavascriptコードを追加します。";
$GLOBALS['TL_LANG']['tl_page']['ga_setdomainname']['0'] = "クッキーのdomainを設定";
$GLOBALS['TL_LANG']['tl_page']['ga_setdomainname']['1'] = "トラッキングのクッキーにこのドメイン名を使用します。";
$GLOBALS['TL_LANG']['tl_page']['ga_addlinktracking']['0'] = "すべての外部のリンクを追跡";
$GLOBALS['TL_LANG']['tl_page']['ga_addlinktracking']['1'] = "すべての外部リンクの追跡を有効にします。重要: これは外部リンクのonClickイベントを削除します。既にgaTrackLinkやgaTrackEventを含んでいる場合だけ削除しません。";
$GLOBALS['TL_LANG']['tl_page']['ga_titlelinktracking']['0'] = "自動的に追跡したリンクのグループ名";
$GLOBALS['TL_LANG']['tl_page']['ga_titlelinktracking']['1'] = "自動的に追跡するイベントの、Googleアナリティクスでのイベントグループの名前です。URLはアクション値として使用します。";
$GLOBALS['TL_LANG']['tl_page']['googleanalytics_legend'] = "Googleアナリティクス";
 
?>
