<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/tl_content.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['0'] = "Vidéos";
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['1'] = "Veuillez choisir la vidéo que vous souhaitez ajouter.";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['0'] = "Description de la vidéo";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['1'] = "Veuillez ajouter une description à la vidéo.";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['0'] = "Alignement de la vidéo";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['1'] = "Veuillez indiquer comment aligner la vidéo.";
$GLOBALS['TL_LANG']['tl_content']['videobox_legend'] = "Vidéo VideoBox";
$GLOBALS['TL_LANG']['CTE']['videos'] = "Eléments vidéo";
$GLOBALS['TL_LANG']['CTE']['videobox']['0'] = "Vidéo VideoBox";
$GLOBALS['TL_LANG']['CTE']['videobox']['1'] = "Ajouter une vidéo VideoBox";
 
?>
