<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/tl_videobox_settings.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_legend'] = "Vidéo Youtube";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['0'] = "Modèle";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['1'] = "Choisissez le modèle pour les vidéos Youtube.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['0'] = "Taille";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['1'] = "Choisissez la taille de la vidéo (largeur x hauteur)";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['0'] = "Voir les vidéos liées";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['1'] = "Définissez si le lecteur doit charger les vidéos liées au début du chargement de la vidéo.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['0'] = "Lecture auto";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['1'] = "Définissez si la vidéo doit se lire automatiquement dès le chargement du lecteur.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['0'] = "Vidéo en boucle";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['1'] = "Ceci à pour conséquence de lire la vidéo en boucle.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['0'] = "Montrer la bordure";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['1'] = "Choisir \"oui\" activera une bordure tout autour du lecteur - en accord avec les couleurs choisis.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['0'] = "Couleur 1";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['1'] = "Cette couleur est la <strong>première</strong> couleur de bordure.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['0'] = "Couleur 2";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['1'] = "Cette couleur est la <strong>seconde</strong> couleur de bordure <strong>et</strong> en même temps la couleur de la barre de contrôle du lecteur.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['0'] = "Quand voulez-vous que la vidéo démmare?";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['1'] = "Ce paramètre permet de déclencher la lecture à partir du nombre de seconde indiqués. Le lecteur déterminera  alors l'image de la vidéo étant la plus proche du temps indiqué, ce qui implique que le lecteur peut se décaler légèrement avant le temps choisi, généralement pas plus de ~2 secondes.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['0'] = "Autoriser le plein écran";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['1'] = "Ceci autorise le bouton de passage de la vidéo en plein écran";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['0'] = "Voir la vidéo en HD";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['1'] = "Cela n'aura bien sur aucun effet, si la vidéo n'est pas disponible en HD.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['0'] = "Voir les informations de la vidéo";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['1'] = "Affiche les informations sur la vidéo comme le titre, la popularité, avant que la vidéo ne démarre.";
 
?>
