<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/tl_videobox.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['0'] = "Titre de la vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['1'] = "Veuillez attribuer un titre à votre vidéo.";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['0'] = "Type de vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['1'] = "Veuillez choisir le type de vidéo que vous souhaitez utiliser.";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['0'] = "ID Youtube";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['1'] = "Saisissez l'ID de votre vidéo Youtube. L'ID est la partie en <strong>gras</strong> de l'url : http://www.youtube.com/watch?v=<strong>SGeZYednWtI</strong>";
$GLOBALS['TL_LANG']['tl_videobox']['title_legend'] = "Paramètres par defaut";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_legend'] = "Vidéo Youtube";
$GLOBALS['TL_LANG']['tl_videobox']['new']['0'] = "Nouvelle vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['new']['1'] = "Créer une nouvelle vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['0'] = "Editer vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['1'] = "Editer la vidéo id %s";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['0'] = "Copier vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['1'] = "Copier la vidéo id %s";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['0'] = "Déplacer vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['1'] = "Déplacer la vidéo id %s";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['0'] = "Effacer vidéo";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['1'] = "Effacer la vidéo id %s";
$GLOBALS['TL_LANG']['tl_videobox']['show']['0'] = "Voir détail";
$GLOBALS['TL_LANG']['tl_videobox']['show']['1'] = "Voir le détail de la vidéo id %s";
 
?>
