<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/tl_videobox_archive.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_archive']['title_legend'] = "Parmètres principaux de l'archive";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['1'] = "Veuillez saisir un titre";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['0'] = "Types des vidéos dans cette archive";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['1'] = "Choisissez les types de vidéo que vous souhaitez activer pour cette archive.";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['0'] = "Permissions";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['1'] = "Les groupes d'utilisateurs cochés auront accès aux vidéos de cette archive dans la liste déroulante, à partir de laquelle vous choisissez les vidéos.";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['0'] = "Editer paramètres";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['1'] = "Editer les paramètres pour l'archive VideoBox id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['0'] = "Nouvelle archive VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['1'] = "Créer une nouvelle archive VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['0'] = "Editer archive VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['1'] = "Editer l'archive VideoBox id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['0'] = "Copier archive VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['1'] = "Copier l'archive VideoBox id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['0'] = "Effacer archive VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['1'] = "Effacer l'archive VideoBox id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['0'] = "Voir détail";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['1'] = "Voir le détail de l'archive VideoBox id %s";
 
?>
