<?php
/**
 * TL_ROOT/system/modules/googleanalytics/languages/fr/default.php 
 * 
 * Contao extension: googleanalytics 1.3.4 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; 2011-2012 Jan Theofel, 2010 ETES GmbH 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Raphael Threis (rthreis), http://threis.be 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['googleanalytics']['0'] = "Intégration de Google Analytics";
$GLOBALS['TL_LANG']['MSC']['gaprivacytext'] = "Ce site utilise Google Analytics. Vous pouvez éviter de tracer vos visites en installant le plugin OptOut pour votre navigateur: <a href=\"http://tools.google.com/dlpage/gaoptout?hl=en\" rel=\"nofollow\">http://tools.google.com/dlpage/gaoptout?hl=de</a>.";
 
?>
