<?php
/**
 * TL_ROOT/system/modules/googleanalytics/languages/fr/tl_page.php 
 * 
 * Contao extension: googleanalytics 1.3.4 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; 2011-2012 Jan Theofel, 2010 ETES GmbH 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Raphael Threis (rthreis), http://threis.be 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['0'] = "ID Google Analytics";
$GLOBALS['TL_LANG']['tl_page']['ga_analyticsid']['1'] = "Identifiant de Google Analytics (format: \"UA-xxxxxxx-x\")";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['0'] = "Cacher l'IP";
$GLOBALS['TL_LANG']['tl_page']['ga_anonymizeip']['1'] = "Cacher l'IP avant de transférer à Google";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['0'] = "Activer tracking chargement de page";
$GLOBALS['TL_LANG']['tl_page']['ga_measurespeed']['1'] = "Permet de mesurer le temps de chargement d'une page.";
$GLOBALS['TL_LANG']['tl_page']['ga_eventtracking']['0'] = "Ajouter un tracking évènementiel";
$GLOBALS['TL_LANG']['tl_page']['ga_externaltracking']['0'] = "Ajouter un tracking externe";
$GLOBALS['TL_LANG']['tl_page']['ga_addlinktracking']['0'] = "Tracer tous les liens externe";
$GLOBALS['TL_LANG']['tl_page']['ga_bounceseconds']['0'] = "Temps de visites détecté comme rebonds (en secondes)";
$GLOBALS['TL_LANG']['tl_page']['ga_bounceseconds']['1'] = "Les visites d'une durée inférieure à ce temps sont considérées comme des rebonds. 0 pour désactiver. Valeurs conseillées : 5-10 secondes.";
$GLOBALS['TL_LANG']['tl_page']['googleanalytics_legend'] = "Google Analytics";
 
?>
