<?php
/**
 * TL_ROOT/system/modules/videobox_vimeo/languages/de/default.php 
 * 
 * Contao extension: videobox_vimeo 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : David Enke 2010 
 * License   : GNU/GPL 
 * Author    : David Enke (david.enke), www.davidenke.de 
 * Translator: David Enke (david.enke), www.davidenke.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['VideoTypes']['vimeo'] = "Vimeo";
$GLOBALS['TL_LANG']['VideoBox']['vimeo_noscript'] = "Leider ist es Ihnen nicht möglich das Video mit dem Titel \"%s\" ohne Javascript anzusehen.";
$GLOBALS['TL_LANG']['VideoBox']['vimeo_noflash'] = "Leider ist es Ihnen nicht möglich das Video mit dem Titel \"%s\" ohne den Adobe Flash Player anzusehen.";
 
?>
