<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/default.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['VideoTypes']['youtube'] = "Youtube";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noscript'] = "Malheureusement, vous ne pourrez pas regarder la vidéo intitulé \"%s\" sans Javascript.";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noflash'] = "Malheureusement, vous ne pourrez pas regarder la vidéo intitulé \"%s\" sans un lecteur Flash installé.";
 
?>
