<?php
/**
 * TL_ROOT/system/modules/videobox/languages/fr/tl_calendar_events.php 
 * 
 * Contao extension: videobox 1.0.0 rc1 
 * French translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_calendar_events']['videobox_addvideo']['0'] = "Ajouter vidéo";
$GLOBALS['TL_LANG']['tl_calendar_events']['videobox_addvideo']['1'] = "Ajouter une vidéo à l'événement.";
$GLOBALS['TL_LANG']['tl_calendar_events']['videobox_video']['0'] = "Vidéos";
$GLOBALS['TL_LANG']['tl_calendar_events']['videobox_video']['1'] = "Veuillez choisir la vidéo que vous souhaitez ajouter.";
$GLOBALS['TL_LANG']['tl_calendar_events']['videobox_legend'] = "Vidéos";
 
?>
