<?php
/**
 * TL_ROOT/system/modules/videobox_vimeo/languages/de/tl_videobox_settings.php 
 * 
 * Contao extension: videobox_vimeo 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : David Enke 2010 
 * License   : GNU/GPL 
 * Author    : David Enke (david.enke), www.davidenke.de 
 * Translator: David Enke (david.enke), www.davidenke.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_legend'] = "Vimeo Video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_template']['0'] = "Template";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_template']['1'] = "Wählen Sie das Template für Youtube Videos.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_size']['0'] = "Größe";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_size']['1'] = "Wählen Sie die Grösse für Youtube Videos (Breite x Höhe).";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_autoplay']['0'] = "Automatisches Abspielen aktivieren?";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_autoplay']['1'] = "Wenn diese Checkbox angewählt ist, wird das Video beim Laden des Players abgespielt.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_color']['0'] = "Farbe";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_color']['1'] = "Diese Farbe färbt den Text und die Steuerung.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showbyline']['0'] = "Zeige Video-Untertitel";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showbyline']['1'] = "Zeigt den Untertitel des Videos vorm abspielen.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showtitle']['0'] = "Zeige Video-Titel";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showtitle']['1'] = "Zeigt den Titel des Videos vorm abspielen.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showportrait']['0'] = "Zeige Benutzerbild";
$GLOBALS['TL_LANG']['tl_videobox_settings']['vimeo_showportrait']['1'] = "Zeigt das Benutzerbild des Videos vorm abspielen.";
 
?>
