<?php
/**
 * TL_ROOT/system/modules/googleanalytics/languages/cs/default.php 
 * 
 * Contao extension: googleanalytics 1.3.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2011-2012 Jan Theofel, 2010 ETES GmbH 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['googleanalytics']['0'] = "Integrace Google Analytics";
$GLOBALS['TL_LANG']['MSC']['gaprivacytext'] = "This website uses Google Analytics. You can avoid tracking your visit by installing the OptOut plugin for your browser: <a href=\"http://tools.google.com/dlpage/gaoptout?hl=en\" rel=\"nofollow\">http://tools.google.com/dlpage/gaoptout?hl=de</a>.";
 
?>
