<?php
/**
 * TL_ROOT/system/modules/videobox/languages/it/default.php 
 * 
 * Contao extension: videobox 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['VideoTypes']['youtube'] = "Youtube";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noscript'] = "Siamo spiacenti, ma non è possibile visualizzare il video \"%s\" senza Javascript";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noflash'] = "Siamo spiacenti, ma non è possibile visualizzare il video \"%s\" senza Adobe Flash Player.";
 
?>
