<?php
/**
 * TL_ROOT/system/modules/videobox/languages/it/tl_content.php 
 * 
 * Contao extension: videobox 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['0'] = "Video";
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['1'] = "Selezionare il video che si vuole aggiungere";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['0'] = "Descrizione del video";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['1'] = "Aggiungere la descrizione del video";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['0'] = "Allineamento video";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['1'] = "Sepcificare l'allineamento del video";
$GLOBALS['TL_LANG']['tl_content']['videobox_legend'] = "Video VideoBox";
$GLOBALS['TL_LANG']['CTE']['videos'] = "Elementi del video";
$GLOBALS['TL_LANG']['CTE']['videobox']['0'] = "Video VideoBox";
$GLOBALS['TL_LANG']['CTE']['videobox']['1'] = "Aggiungi un video della libreria VideoBox";
 
?>
