<?php
/**
 * TL_ROOT/system/modules/videobox/languages/it/tl_videobox_archive.php 
 * 
 * Contao extension: videobox 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_archive']['title_legend'] = "Impostazioni globali dell'archivio";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['1'] = "Indicare il titolo dell'archivio";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['0'] = "Tipologia archivio";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['1'] = "Indicare il tipo di video di questo archivio";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['0'] = "Permessi";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['1'] = "Selezionare i gruppi di utente che avranno l'accesso all'archivio";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['0'] = "Modifica impostazioni";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['1'] = "Modifica le impostazioni impostazioni per l'archivio VideoBox con id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['0'] = "Nuovo archivio VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['1'] = "Crea un nuovo archivio VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['0'] = "Modifica archivio VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['1'] = "Modifica l'archivio VideoBox con id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['0'] = "Copia l'archivio VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['1'] = "Copia l'archivio VideoBox con id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['0'] = "Elimina l'archivio VideoBox";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['1'] = "Elimina l'archivio VideoBox con id %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['0'] = "Mostra dettagli";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['1'] = "Mostra i dettagli dell'archivio VideoBox con id %s";
 
?>
