<?php
/**
 * TL_ROOT/system/modules/videobox/languages/it/tl_videobox_settings.php 
 * 
 * Contao extension: videobox 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_legend'] = "Video Youtube";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['0'] = "Template";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['1'] = "Seleziona il template per i video Youtube";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['0'] = "Dimensioni";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['1'] = "Selezionare le dimensioni per il video (larghezza ed altezza)";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['0'] = "Mostra video correlati";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['1'] = "Permette di visionare i video correlati una volta che il visitatore ha visto il video caricato";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['0'] = "Autoplay";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['1'] = "Imposta il video per essere avviato in modo automatico";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['0'] = "Riproduzione continua";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['1'] = "Selezionando questa opzione il video verrà riprodotto in modo continuativo";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['0'] = "Mostra bordi";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['1'] = "Selezionando questa opzione è possibile aggiungere i bordi al player del video.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['0'] = "Colore primario";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['1'] = "Colore primario per il bordo del video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['0'] = "Colore secondario";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['1'] = "Colore secondario del video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['0'] = "Partenza del video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['1'] = "Questo parametro consente di iniziare la riproduzione del video in un determinato punto dall'inizio del video. Il player cercherà il fotogramma più vicino all'intervallo di tempo  specificato. Questo significa che a volte ci può essere uno scostamento rispetto a quanto richiesto, generalmente non più di ~2 secondi.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['0'] = "Abilita visualizzazione a schermo intero";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['1'] = "Questa opzione permette di abilitare la visione a schermo intero";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['0'] = "Mostra video in HD";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['1'] = "Questa opzione permette di abilitare la visione dei video in HD. L'opzione non ha effetto se il video non è disponibile in questa modalità.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['0'] = "Mostra informazioni video";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['1'] = "Visualizzare le informazioni come titolo e la valutazione prima che il video venga riprodotto.";
 
?>
