<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/modules.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['videobox']['0'] = "VideoBox";
$GLOBALS['TL_LANG']['MOD']['videobox']['1'] = "Denna modul låter dig förvandla din TYPOlight till ett videohanteringssystem.";
 
?>
