<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/tl_content.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['0'] = "Videofilmer";
$GLOBALS['TL_LANG']['tl_content']['videobox_video']['1'] = "Välj den videofilm som du vill lägga till.";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['0'] = "Beskrivning av videofilm";
$GLOBALS['TL_LANG']['tl_content']['videobox_description']['1'] = "Lägg till en beskrivning av videofilmen.";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['0'] = "Justering av videofilmen";
$GLOBALS['TL_LANG']['tl_content']['videobox_floating']['1'] = "Välj justering av videofilmen.";
$GLOBALS['TL_LANG']['tl_content']['videobox_legend'] = "VideoBox-videofilm";
$GLOBALS['TL_LANG']['CTE']['videos'] = "Videofilm-element";
$GLOBALS['TL_LANG']['CTE']['videobox']['0'] = "VideoBox-videofilm";
$GLOBALS['TL_LANG']['CTE']['videobox']['1'] = "Lägg till en VideoBox-videofilm";
 
?>
