<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/default.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['VideoTypes']['youtube'] = "Youtube";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noscript'] = "Tyvärr kan du inte se videofilmen \"%s\" utan att ha JavaScript påslaget i din webbläsare.";
$GLOBALS['TL_LANG']['VideoBox']['youtube_noflash'] = "Tyvärr kan du inte se videofilmen \"%s\" utan att ha tillägget Adobe Flash Player installerad i din webbläsare.";
 
?>
