<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/tl_news.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_news']['videobox_addvideo']['0'] = "Lägg till videofilm";
$GLOBALS['TL_LANG']['tl_news']['videobox_addvideo']['1'] = "Lägg till videofilm i händelsen.";
$GLOBALS['TL_LANG']['tl_news']['videobox_video']['0'] = "Videofilmer";
$GLOBALS['TL_LANG']['tl_news']['videobox_video']['1'] = "Välj den videofilm som du vill lägga till.";
$GLOBALS['TL_LANG']['tl_news']['videobox_legend'] = "Videofilmer";
 
?>
