<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/tl_videobox.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['0'] = "Videofilmtitel";
$GLOBALS['TL_LANG']['tl_videobox']['videotitle']['1'] = "Ange en titel för videofilmen.";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['0'] = "Videoformat";
$GLOBALS['TL_LANG']['tl_videobox']['videotype']['1'] = "Välj format för videofilmen.";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['0'] = "YouTube-ID";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_id']['1'] = "Ange ID för din YouTube-videofilm. ID är den del av videofilmens URL som markerats med <strong>fet</strong> stil i följande exempel: http://www.youtube.com/watch?v=<strong>SGeZYednWtI</strong>";
$GLOBALS['TL_LANG']['tl_videobox']['title_legend'] = "Standardinställningar";
$GLOBALS['TL_LANG']['tl_videobox']['youtube_legend'] = "YouTube-videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['new']['0'] = "Ny videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['new']['1'] = "Skapa en ny videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['0'] = "Redigera videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['edit']['1'] = "Redigera videofilm med ID %s";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['0'] = "Kopiera videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['copy']['1'] = "Kopiera videofilm med ID %s";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['0'] = "Flytta videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['cut']['1'] = "Flytta videofilm med ID %s";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['0'] = "Radera videofilm";
$GLOBALS['TL_LANG']['tl_videobox']['delete']['1'] = "Radera videofilm med ID %s";
$GLOBALS['TL_LANG']['tl_videobox']['show']['0'] = "Visa detaljer";
$GLOBALS['TL_LANG']['tl_videobox']['show']['1'] = "Visa detaljer för videofilm med ID %s";
 
?>
