<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/tl_videobox_archive.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_archive']['title_legend'] = "Globala arkivinställningar";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_videobox_archive']['title']['1'] = "Ange en titel för arkivet.";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['0'] = "Videoformat i detta arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['activeVideoTypes']['1'] = "Välj videoformat som ska användas i detta arkiv.";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['0'] = "Tillåtna medlemsgrupper";
$GLOBALS['TL_LANG']['tl_videobox_archive']['allowedUserGroups']['1'] = "Markerade användargrupper kommer att kunna välja videofilmer från detta arkiv.";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['0'] = "Redigera inställningar";
$GLOBALS['TL_LANG']['tl_videobox_archive']['editvideosettings']['1'] = "Redigera inställningarna för VideoBox-arkiv med ID %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['0'] = "Nytt VideoBox-arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['new']['1'] = "Skapa ett nytt VideoBox-arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['0'] = "Redigera VideoBox-arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['edit']['1'] = "Redigera VideoBox-arkiv med ID %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['0'] = "Kopiera VideoBox-arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['copy']['1'] = "Kopiera VideoBox-arkiv med ID %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['0'] = "Radera VideoBox-arkiv";
$GLOBALS['TL_LANG']['tl_videobox_archive']['delete']['1'] = "Radera VideoBox-arkiv med ID %s";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['0'] = "Visa detaljer";
$GLOBALS['TL_LANG']['tl_videobox_archive']['show']['1'] = "Visa detaljer för VideoBox-arkiv med ID %s";
 
?>
