<?php
/**
 * TL_ROOT/system/modules/videobox/languages/sv/tl_videobox_settings.php 
 * 
 * Contao extension: videobox 1.0.2 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010, Yanick Witschi, certo web & design GmbH 
 * License   : LGPL 
 * Author    : Yanick Witschi (Toflar), http://www.certo-net.ch 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_legend'] = "YouTube-videofilm";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['0'] = "Mall";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_template']['1'] = "Välj mall för YouTube-videofilmer.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['0'] = "Storlek";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_size']['1'] = "Välj storlek för videofilm (bredd x höjd).";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['0'] = "Visa relaterade videofilmer";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_rel']['1'] = "Markeras om videospelaren ska visa relaterade videofilmer efter att den valda filmen spelats till sitt slut.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['0'] = "Autouppspelning";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_autoplay']['1'] = "Markeras om uppspelning av den valda videofilmen ska starta automatiskt när videospelaren laddats.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['0'] = "Repetera videouppspelningen";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_loop']['1'] = "Markeras om uppspelningen automatiskt ska börja om från början efter att videofilmen spelats till sitt slut.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['0'] = "Visa ramar";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_border']['1'] = "Markeras för att lägga till en ram runt hela videospelaren. Var uppmärksam på färgerna!";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['0'] = "Färg 1";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color1']['1'] = "Denna färg är den <strong>primära</strong> ramfärgen.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['0'] = "Färg 2";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_color2']['1'] = "Denna färg är den <strong>sekundära</strong> ramfärgen <strong>och</strong> även bakgrundsfärg till videospelarens kontroll-knappar.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['0'] = "Tidsstämpel för uppspelningsstart";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_start']['1'] = "Denna parameter får videospelaren att börja uppspelningen vid angiven tidsstämpel (sekunder från start). Notera att videospelaren letar efter närmsta intilligande keyframe och att uppspelningen då kan börja strax före den inställda tidsstämpeln. Vanligtvis inte mer än ~2 sekunder före.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['0'] = "Tillåt fullskärmsläge";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_fs']['1'] = "Markeras om knappen för fullskärmsläge ska vara tillgänglig.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['0'] = "Visa videofilm i HD";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_hd']['1'] = "Markera om videofilmen ska visas i HD-format. Har ingen effekt om inte videofilmen finns tillgänglig i HD.";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['0'] = "Visa videofilmsinformation";
$GLOBALS['TL_LANG']['tl_videobox_settings']['youtube_showinfo']['1'] = "Visa information om bl.a. titel och betyg innan uppspelningen startar.";
 
?>
