<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_formdata.php 
 * 
 * Contao extension: efg 1.14.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2010 Thomas Kuhn 
 * License   : GNU LGPL V3 
 * Author    : Thomas Kuhn (tom) 
 * Translator: Thomas Kuhn (tom) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_formdata']['form']['0'] = "Formular";
$GLOBALS['TL_LANG']['tl_formdata']['form']['1'] = "Daten aus Formular";
$GLOBALS['TL_LANG']['tl_formdata']['date']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_formdata']['date']['1'] = "Datum des Eintrags";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['0'] = "IP-Adresse";
$GLOBALS['TL_LANG']['tl_formdata']['ip']['1'] = "IP-Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['0'] = "Bemerkung";
$GLOBALS['TL_LANG']['tl_formdata']['be_notes']['1'] = "Bemerkungen, Bearbeitungshinweise etc.";
$GLOBALS['TL_LANG']['tl_formdata']['import_source']['0'] = "Quelldatei";
$GLOBALS['TL_LANG']['tl_formdata']['import_source']['1'] = "Bitte wählen Sie die zu importierende CSV-Datei aus der Dateiübersicht.";
$GLOBALS['TL_LANG']['tl_formdata']['import_preview']['0'] = "Vorschau und Feldzuordnung";
$GLOBALS['TL_LANG']['tl_formdata']['import_preview']['1'] = "Bitte wählen Sie, in welche Formulardaten-Felder die Spalten der CSV-Datei importiert werden sollen. Die nachfolgende Tabelle zeigt maximal 50 Zeilen der CSV-Datei.";
$GLOBALS['TL_LANG']['tl_formdata']['csv_has_header']['0'] = "Datei mit Spaltenbeschriftungen";
$GLOBALS['TL_LANG']['tl_formdata']['csv_has_header']['1'] = "Die Datei enthält in der ersten Zeile Feld-/Spaltenbeschriftungen.";
$GLOBALS['TL_LANG']['tl_formdata']['option_import_ignore'] = "-nicht importieren-";
$GLOBALS['TL_LANG']['tl_formdata']['published']['0'] = "Veröffentlicht";
$GLOBALS['TL_LANG']['tl_formdata']['published']['1'] = "Dieses Kennzeichen kann als Einschränkung bei Verwendung einer Auflistung verwendet werden.";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['0'] = "Mitglied";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member']['1'] = "Mitglied als Besitzer des Datensatzes";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['0'] = "Benutzer";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user']['1'] = "Benutzer als Besitzer des Datensatzes";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member_group']['0'] = "Mitgliedergruppe";
$GLOBALS['TL_LANG']['tl_formdata']['fd_member_group']['1'] = "Mitgliedergruppe als Besitzer des Datensatzes";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user_group']['0'] = "Benutzergruppe";
$GLOBALS['TL_LANG']['tl_formdata']['fd_user_group']['1'] = "Benutzergruppe als Besitzer des Datensatzes";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_formdata']['alias']['1'] = "Der Alias eines Eintrags ist eine eindeutige Referenz, die anstelle der Eintrags-ID aufgerufen werden kann.";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['0'] = "Absender";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sender']['1'] = "E-Mail-Adresse des Absenders";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['0'] = "Empfänger";
$GLOBALS['TL_LANG']['tl_formdata']['mail_recipient']['1'] = "E-Mail-Adresse des Empfängers";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['0'] = "Betreff";
$GLOBALS['TL_LANG']['tl_formdata']['mail_subject']['1'] = "Betreffzeile der E-Mail";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['0'] = "Nachricht (Plain Text)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_plaintext']['1'] = "Text der E-Mail im Text-Format";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['0'] = "Nachricht (HTML)";
$GLOBALS['TL_LANG']['tl_formdata']['mail_body_html']['1'] = "Text der E-Mail im HTML-Format";
$GLOBALS['TL_LANG']['tl_formdata']['attachments'] = "Datei-Anhang";
$GLOBALS['TL_LANG']['tl_formdata']['new']['0'] = "Neuer Eintrag";
$GLOBALS['TL_LANG']['tl_formdata']['new']['1'] = "Einen neuen Eintrag erstellen";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['0'] = "Eintrag bearbeiten";
$GLOBALS['TL_LANG']['tl_formdata']['edit']['1'] = "Eintrag ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['0'] = "Eintrag duplizieren";
$GLOBALS['TL_LANG']['tl_formdata']['copy']['1'] = "Eintrag ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['0'] = "Eintrag löschen";
$GLOBALS['TL_LANG']['tl_formdata']['delete']['1'] = "Eintrag ID %s löschen";
$GLOBALS['TL_LANG']['tl_formdata']['show']['0'] = "Eintrag anzeigen";
$GLOBALS['TL_LANG']['tl_formdata']['show']['1'] = "Details des Eintrags ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['0'] = "Bestätigungs-Mail versenden";
$GLOBALS['TL_LANG']['tl_formdata']['mail']['1'] = "Bestätigungs-Mail für Eintrag ID %s versenden";
$GLOBALS['TL_LANG']['tl_formdata']['import']['0'] = "CSV-Import";
$GLOBALS['TL_LANG']['tl_formdata']['import']['1'] = "Daten aus einer CSV-Datei importieren";
$GLOBALS['TL_LANG']['tl_formdata']['export']['0'] = "CSV-Export";
$GLOBALS['TL_LANG']['tl_formdata']['export']['1'] = "Daten als CSV-Datei exportieren";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['0'] = "Excel Export";
$GLOBALS['TL_LANG']['tl_formdata']['exportxls']['1'] = "Daten als MS-Excel-Datei exportieren";
$GLOBALS['TL_LANG']['tl_formdata']['mail_sent'] = "Mail-Versand erfolgt an %s";
$GLOBALS['TL_LANG']['tl_formdata']['confirmation_sent'] = "Für diesen Eintrag wurde bereits eine Bestätigungs-Mail gesendet am %s um %s";
$GLOBALS['TL_LANG']['tl_formdata']['confirmationSent']['0'] = "Bestätigungs-Mail gesendet";
$GLOBALS['TL_LANG']['tl_formdata']['confirmationSent']['1'] = "Eine Bestätigungs-Mail für diesen Eintrag wurde gesendet";
$GLOBALS['TL_LANG']['tl_formdata']['confirmationDate']['0'] = "Bestätigungs-Mail gesendet am";
$GLOBALS['TL_LANG']['tl_formdata']['confirmationDate']['1'] = "Der Zeitpunkt des Versands der Bestätigungs-Mail";
$GLOBALS['TL_LANG']['tl_formdata']['import_confirm'] = "%s neue Einträge wurden importiert.";
$GLOBALS['TL_LANG']['tl_formdata']['import_invalid'] = "%s  ungültige Einträge wurden übersprungen.";
$GLOBALS['TL_LANG']['tl_formdata']['error_select_source'] = "Bitte wählen Sie eine Quelldatei!";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['0'] = "Details";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_details']['1'] = "Details anzeigen";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['0'] = "Bearbeiten";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_edit']['1'] = "Datensatz bearbeiten";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['0'] = "Löschen";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_delete']['1'] = "Datensatz löschen";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['0'] = "CSV Export";
$GLOBALS['TL_LANG']['tl_formdata']['fe_link_export']['1'] = "Daten als CSV-Datei exportieren";
$GLOBALS['TL_LANG']['tl_formdata']['fe_deleteConfirm'] = "Soll der Eintrag wirklich gelöscht werden?";
$GLOBALS['TL_LANG']['tl_formdata']['confirmation_legend'] = "Bestätigungs-Mail";
$GLOBALS['TL_LANG']['tl_formdata']['fdNotes_legend'] = "Bemerkung";
$GLOBALS['TL_LANG']['tl_formdata']['fdOwner_legend'] = "Besitzer";
$GLOBALS['TL_LANG']['tl_formdata']['fdDetails_legend'] = "Details";
 
?>
