<?php
/**
 * TL_ROOT/system/modules/efg/languages/de/tl_module.php
 *
 * Contao extension: efg 1.14.0 stable
 * Deutsch translation file
 *
 * Copyright : (c) 2010 Thomas Kuhn
 * License   : GNU LGPL V3
 * Author    : Thomas Kuhn (tom)
 * Translator: Thomas Kuhn (tom)
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_module']['efgSearch_legend'] = "Sucheinstellungen";
$GLOBALS['TL_LANG']['tl_module']['comments_legend'] = "Kommentare";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['0'] = "Formular-Daten-Tabelle";
$GLOBALS['TL_LANG']['tl_module']['list_formdata']['1'] = "Bitte wählen Sie die Formular-Daten-Tabelle, deren Datensätze Sie auflisten möchten.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['0'] = "Felder";
$GLOBALS['TL_LANG']['tl_module']['efg_list_fields']['1'] = "Bitte wählen Sie die Felder, die Sie auflisten möchten.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['0'] = "Typ des Such-Formulars";
$GLOBALS['TL_LANG']['tl_module']['efg_list_searchtype']['1'] = "Bitte wählen Sie, welchen Typ des Such-Formulars Sie verwenden möchten.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['0'] = "Durchsuchbare Felder";
$GLOBALS['TL_LANG']['tl_module']['efg_list_search']['1'] = "Bitte wählen Sie die Felder, die im Frontend durchsuchbar sein sollen.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['0'] = "Felder der Detailseite";
$GLOBALS['TL_LANG']['tl_module']['efg_list_info']['1'] = "Bitte wählen Sie die Felder, die Sie auf der Detailseite anzeigen möchten. Wählen Sie kein Feld, um die Detailansicht eines Datensatzes zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['0'] = "Verzeichnis der Icons";
$GLOBALS['TL_LANG']['tl_module']['efg_iconfolder']['1'] = "Tragen Sie hier das Verzeichnis Ihrer Icons ein. Falls das Feld nicht ausgefüllt wird, werden die Icons im Verzeichnis \"system/modules/efg/html/\" verwendet.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_keep_id']['0'] = "Datensatz-ID beibehalten bei Frontendbearbeitung";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_keep_id']['1'] = "Bei der Frontendbearbeitung wird normalerweise ein neuer Datensatz -somit neue ID- angelegt, anschließend der alte gelöscht. Wählen Sie diese Option, falls Sie auf eine unveränderte Datensatz-ID angewiesen sind.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_no_formatted_mail']['0'] = "Kein Versand per E-Mail (formatierter Text / HTML) bei Frontend-Bearbeitung";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_no_formatted_mail']['1'] = "Wählen Sie diese Option, wenn der im Formulargenerator eingestellte Versand per E-Mail (formatierter Text / HTML) bei Frontend-Bearbeitung nicht erfolgen soll.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_no_confirmation_mail']['0'] = "Kein Versand der Bestätigung per E-Mail bei Frontend-Bearbeitung";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_no_confirmation_mail']['1'] = "Wählen Sie diese Option, wenn der im Formulargenerator eingestellte Versand einer Bestätigungs-Mail bei Frontend-Bearbeitung nicht erfolgen soll.";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['0'] = "Anzeige Einschränkung";
$GLOBALS['TL_LANG']['tl_module']['efg_list_access']['1'] = "Wählen Sie, welche Daten angezeigt werden dürfen.";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['0'] = "URL-Fragment der Detailseite";
$GLOBALS['TL_LANG']['tl_module']['efg_DetailsKey']['1'] = "Anstelle der Vorgabe \"details\" in der URL der Auflistungs-Detailseite können Sie hier einen abweichenden Begriff angeben.<br />Dadurch kann z.B. eine URL www.domain.tld/page/<b>info</b>/alias.html statt der Standard-URL www.domain.tld/page/<b>details</b>/alias.html erzeugt werden";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['0'] = "Bearbeitung im Frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_edit_access']['1'] = "Wählen Sie, ob Daten im Frontend bearbeitet werden dürfen.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['0'] = "Löschen im Frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_delete_access']['1'] = "Wählen Sie, ob Daten im Frontend gelöscht werden dürfen.";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['0'] = "CSV-Export im Frontend";
$GLOBALS['TL_LANG']['tl_module']['efg_fe_export_access']['1'] = "Wählen Sie, ob Daten im Frontend als CSV-Datei exportiert werden dürfen.";
$GLOBALS['TL_LANG']['tl_module']['efg_com_allow_comments']['0'] = "Kommentare aktivieren";
$GLOBALS['TL_LANG']['tl_module']['efg_com_allow_comments']['1'] = "Besuchern das Kommentieren von Einträgen erlauben.";
$GLOBALS['TL_LANG']['tl_module']['com_moderate']['0'] = "Kommentare moderieren";
$GLOBALS['TL_LANG']['tl_module']['com_moderate']['1'] = "Kommentare erst nach Bestätigung auf der Webseite veröffentlichen.";
$GLOBALS['TL_LANG']['tl_module']['com_bbcode']['0'] = "BBCode erlauben";
$GLOBALS['TL_LANG']['tl_module']['com_bbcode']['1'] = "Besuchern das Formatieren ihrer Kommentare mittels BBCode erlauben.";
$GLOBALS['TL_LANG']['tl_module']['com_requireLogin']['0'] = "Login zum Kommentieren benötigt";
$GLOBALS['TL_LANG']['tl_module']['com_requireLogin']['1'] = "Nur angemeldeten Benutzern das Erstellen von Kommentaren erlauben.";
$GLOBALS['TL_LANG']['tl_module']['com_disableCaptcha']['0'] = "Sicherheitsfrage deaktivieren";
$GLOBALS['TL_LANG']['tl_module']['com_disableCaptcha']['1'] = "Wählen Sie diese Option nur, wenn das Erstellen von Kommentaren auf authentifizierte Benutzer beschränkt ist.";
$GLOBALS['TL_LANG']['tl_module']['efg_com_per_page']['0'] = "Kommentare pro Seite";
$GLOBALS['TL_LANG']['tl_module']['efg_com_per_page']['1'] = "Anzahl an Kommentaren pro Seite. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_module']['com_order']['0'] = "Sortierung";
$GLOBALS['TL_LANG']['tl_module']['com_order']['1'] = "Standardmäßig werden Kommentare aufsteigend sortiert, beginnend mit dem ältesten.";
$GLOBALS['TL_LANG']['tl_module']['com_template']['0'] = "Kommentartemplate";
$GLOBALS['TL_LANG']['tl_module']['com_template']['1'] = "Hier können Sie das Kommentartemplate auswählen.";
$GLOBALS['TL_LANG']['tl_module']['efg_com_notify']['0'] = "Benachrichtigung an";
$GLOBALS['TL_LANG']['tl_module']['efg_com_notify']['1'] = "Bitte legen Sie fest, wer beim Hinzufügen neuer Kommentare benachrichtigt wird.";
$GLOBALS['TL_LANG']['tl_module']['notify_admin'] = "Systemadministrator";
$GLOBALS['TL_LANG']['tl_module']['notify_author'] = "Besitzer des Eintrags";
$GLOBALS['TL_LANG']['tl_module']['notify_both'] = "Besitzer und Systemadministrator";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['0'] = "Keine Suche";
$GLOBALS['TL_LANG']['efg_list_searchtype']['none']['1'] = "Kein Suchformular";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['0'] = "Dropdown und Eingabefeld";
$GLOBALS['TL_LANG']['efg_list_searchtype']['dropdown']['1'] = "Das Suchformular enthält ein DropDown zur Auswahl des zu durchsuchenden Feldes und ein Eingabefeld für den Suchbegriff.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['0'] = "Einzelnes Eingabefeld";
$GLOBALS['TL_LANG']['efg_list_searchtype']['singlefield']['1'] = "Das Suchformular enthält ein einzelndes Eingabefeld für den Suchbegriff. Bei der Suche werden alle als durchsuchbare Felder definierten Felder berücksichtigt.";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['0'] = "Mehrere Eingabefelder";
$GLOBALS['TL_LANG']['efg_list_searchtype']['multiplefields']['1'] = "Das Suchformular enthält für jedes durchsuchbare Feld ein separates Eingabefeld für den Suchbegriff.";
$GLOBALS['TL_LANG']['efg_list_access']['public']['0'] = "Öffentlich";
$GLOBALS['TL_LANG']['efg_list_access']['public']['1'] = "Jeder Seitenbesucher darf alle Daten sehen.";
$GLOBALS['TL_LANG']['efg_list_access']['member']['0'] = "Besitzer";
$GLOBALS['TL_LANG']['efg_list_access']['member']['1'] = "Mitglieder dürfen nur ihre eigenen Daten sehen.";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['0'] = "Gruppen-Mitglieder";
$GLOBALS['TL_LANG']['efg_list_access']['groupmembers']['1'] = "Mitglieder dürfen ihre eigenen und die Daten ihrer Gruppen-Mitglieder sehen.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['0'] = "Keine Bearbeitung";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['none']['1'] = "Daten können nicht im Frontend bearbeitet werden.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['0'] = "Öffentlich";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['public']['1'] = "Jeder Seitenbesucher darf alle Daten bearbeiten.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['0'] = "Besitzer";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['member']['1'] = "Mitglieder dürfen nur ihre eigenen Daten bearbeiten.";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['0'] = "Gruppen-Mitglieder";
$GLOBALS['TL_LANG']['efg_fe_edit_access']['groupmembers']['1'] = "Mitglieder dürfen ihre eigenen und die Daten ihrer Gruppen-Mitglieder bearbeiten.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['0'] = "Kein Löschen";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['none']['1'] = "Daten können nicht im Frontend gelöscht werden.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['0'] = "Öffentlich";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['public']['1'] = "Jeder Seitenbesucher darf alle Daten löschen.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['0'] = "Besitzer";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['member']['1'] = "Mitglieder dürfen nur ihre eigenen Daten löschen.";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['0'] = "Gruppen-Mitglieder";
$GLOBALS['TL_LANG']['efg_fe_delete_access']['groupmembers']['1'] = "Mitglieder dürfen ihre eigenen und die Daten ihrer Gruppen-Mitglieder löschen.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['0'] = "Kein Export";
$GLOBALS['TL_LANG']['efg_fe_export_access']['none']['1'] = "Daten können nicht im Frontend exportiert werden.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['0'] = "Öffentlich";
$GLOBALS['TL_LANG']['efg_fe_export_access']['public']['1'] = "Jeder Seitenbesucher darf alle Daten exportieren.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['0'] = "Besitzer";
$GLOBALS['TL_LANG']['efg_fe_export_access']['member']['1'] = "Mitglieder dürfen nur ihre eigenen Daten exportieren.";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['0'] = "Gruppen-Mitglieder";
$GLOBALS['TL_LANG']['efg_fe_export_access']['groupmembers']['1'] = "Mitglieder dürfen ihre eigenen und die Daten ihrer Gruppen-Mitglieder exportieren.";

?>
